#ifndef REALMODE_H_
#define REALMODE_H_

#define BOOT_SIGNATURE_OFFSET 		0x1FE
#define BOOT_SIGNATURE_MAGIC		0xAA55

#define REALMODE_SEGMENT			0x00


#define REALMODE_STACK_TOP			0x9F000
#define REALMODE_STACK_BOTTOM		0x49E00
#define REALMODE_STACK_LENGTH		0x55200

#define REALMODE_HEAP_START			0x17E00
#define REALMODE_HEAP_END			0x49DFF
#define REALMODE_HEAP_LENGTH		0x32000

#define REALMODE_KERNEL_START		0x2700
#define REALMODE_KERNEL_END			0x17DFF
#define REALMODE_KERNEL_LENGTH		0x15700

#define REALMODE_STAGEZERO_START		0x7C00
#define REALMODE_STAGEZERO_END			0x7DFF
#define REALMODE_STAGEZERO_LENGTH		0x200

#define REALMODE_STAGEONE_START			0x500
#define REALMODE_STAGEONE_END			0x26FF
#define REALMODE_STAGEONE_LENGTH		0x2200

#endif